import Head from 'next/head';
import {PageBackground} from '../components/background.js'
import {Header} from '../components/header'
import {Footer} from '../components/footer'

export default function App() {
  return (
    <div style={{width: '100%', background: '#020221'}}>
        <Head>
            <title>ioToad</title>
            <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        </Head>
        <PageBackground />
        <main style={{position: 'absolute', width: '100%'}}>
          <Header />
          <div style={{display: 'grid', placeItems: 'center', marginTop: '50px'}}>
            <div style={{color: '#f8f172', textAlign: 'center', maxWidth: '800px'}}>
                <h1>ioToad</h1>
                <h3>Real Assistance for Virtual Construction</h3>
                <p>.............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... .............
                .............. ........ .......... ............. </p>
            </div>
          </div>
          <Footer />
        </main>
    </div>
  );
}
